AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TuCita 247 App Reports

Parameters:
  UserPoolId:
    Type: String
    Description: User poolID for Cognito provider
  Audience:
    Type: String
    Description: Client id for user pool

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.8
    Environment:
        Variables:
            devCors: "http://localhost:4200"
            prodCors: "https://dev-console.tucita247.com"
    VpcConfig:
      SecurityGroupIds: 
        - sg-ecf44cd2
      SubnetIds: 
        - subnet-606ac106
        - subnet-6af4454b
        - subnet-398ff474
        - subnet-9a8f3bc5

Resources:
  HttpApi:
    ApiId: HttpApi
    Type: AWS::Serverless::HttpApi
    Name: TuCita247Repo
    Properties:
      Domain:
        DomainName: dev-apirep.tucita247.com
        CertificateArn: arn:aws:acm:us-east-1:374759743337:certificate/74aec86a-dbe8-4036-bef2-e2d0f63c17b4
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z0264003CIKJOX1E9XTX
      Auth:
        # DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            # AuthorizationScopes:
            #   - email
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${AWS::Region}_${UserPoolId}
              audience:
                - !Ref Audience
      CorsConfiguration:
        AllowMethods:
          - GET
          - PUT
          - PATCH
          - DELETE
          - POST
        AllowOrigins:
          - http://localhost:4200
          - https://dev-console.tucita247.com
          - https://tucita247.com
        AllowHeaders:
          - content-type
          - authorization
        MaxAge: "10"
        AllowCredentials: True
  
  GetRepoAverageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetRepoAverage
      CodeUri: getRepoAverage/
      Handler: getRepoAverage.lambda_handler
      Role: arn:aws:iam::374759743337:role/LambdaDynamo
      Layers: 
        - arn:aws:lambda:us-east-1:374759743337:layer:boto3:2
        # - arn:aws:lambda:us-east-1:821843840552:layer:botocore:1
        - arn:aws:lambda:us-east-1:374759743337:layer:dynamodb-json:1
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /appointments/repAverage/{businessId}/{locationId}/{providerId}/{dateIni}/{dateFin}/{lastItem}
            Method: get
            ApiId: !Ref HttpApi

  GetRepoVisitasFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetRepoVisitas
      CodeUri: getRepoVisitas/
      Handler: getRepoVisitas.lambda_handler
      Role: arn:aws:iam::374759743337:role/LambdaDynamo
      Layers: 
        - arn:aws:lambda:us-east-1:374759743337:layer:boto3:2
        # - arn:aws:lambda:us-east-1:821843840552:layer:botocore:1
        - arn:aws:lambda:us-east-1:374759743337:layer:dynamodb-json:1
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /appointments/repVisitas/{businessId}/{locationId}/{providerId}/{dateIni}/{dateFin}/{lastItem}
            Method: get
            ApiId: !Ref HttpApi

  GetRepoCancelFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetRepoCancel
      CodeUri: getRepoCancel/
      Handler: getRepoCancel.lambda_handler
      Role: arn:aws:iam::374759743337:role/LambdaDynamo
      Layers: 
        - arn:aws:lambda:us-east-1:374759743337:layer:boto3:2
        # - arn:aws:lambda:us-east-1:821843840552:layer:botocore:1
        - arn:aws:lambda:us-east-1:374759743337:layer:dynamodb-json:1
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /appointments/repCancel/{businessId}/{locationId}/{providerId}/{dateIni}/{dateFin}/{lastItem}
            Method: get
            ApiId: !Ref HttpApi
            